// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znkignxkfzeueoawjvfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpua2lnbnhrZnpldWVvYXdqdmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTAwMjEsImV4cCI6MjA1ODI2NjAyMX0.CFMEamKRpKRSmxAYLoFl8XPC1XEcY8lAgQVuU4s1CE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);